module.exports = {
  clearMocks: true,
  moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx', 'node'],
  testEnvironment: 'node',
  preset: 'ts-jest',
  verbose: true,
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    '**/*.{js,ts}',
    '!**/*.d.{js,ts}',
    '!**/node_modules/**',
    '!**/coverage/**',
    '!**/src/config/**',
    '!**/src/entities/**',
    '!**/src/enums/**',
    '!**/src/exceptions/**',
    '!**/src/http/**',
    '!**/src/models/**',
    '!**/src/routes/**',
    '!jest.config.js',
    '!**/src/server.ts',
    '!**/src/container.ts',
    '!**/src/index.ts',
  ],
}
