CREATE TABLE users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	phone varchar(32) NOT NULL,
	email varchar(64) NOT NULL,
	password varchar(64) NOT NULL,
	active SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	name varchar(255) NOT NULL,
	price float NOT NULL,
	active SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE clients (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	name varchar(255) NOT NULL,
	phone varchar(32),
	email varchar(255),
	active SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE sales (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	product_id int NOT NULL,
	client_id int NOT NULL,
	discount float DEFAULT 0.00,
	price float NOT NULL,
	paid float NOT NULL,
	active SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (product_id) REFERENCES products(id),
	FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE schedules (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	client_id int NOT NULL,
	name varchar(255) NOT NULL,
	description varchar(512),
	date TIMESTAMP,
	active SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (client_id) REFERENCES clients(id)
);
